### ISSUE TITLE
NullPointerException in BTreeMap.get()

### ISSUE THREAD

**Issue by pcernocky** [batterseapower/btreemap#5]
This code:
```java
    BTreeMap<Integer, Integer> map = BTreeMap.create();

    for (int i = 0; i < 1000; i++) {
      map.put(i, i);
    }

    for (int i = 0; i < 481; i++) {
      map.remove(i);
    }

    map.get(481);  // this line fails with NullPointerException
```

fails with exception:

```
Exception in thread "main" java.lang.NullPointerException
	at uk.co.omegaprime.btreemap.BTreeMap$Internal.find(BTreeMap.java:221)
	at uk.co.omegaprime.btreemap.BTreeMap.findLeaf(BTreeMap.java:491)
	at uk.co.omegaprime.btreemap.BTreeMap.getOrDefault(BTreeMap.java:501)
	at uk.co.omegaprime.btreemap.BTreeMap.get(BTreeMap.java:470)
	at Test.main(Test.java:22)
```

**Comment by batterseapower** [comment]
You're right. It's not immediately clear to me why this happens.
